### ISSUE TITLE
Compatibility with Firefox?

### ISSUE THREAD

**Issue by amirf147** [HenryGetz/GeminiPilot#2]
Hi, thanks for sharing your script. Unfortunately i am unable to get it running on the latest version of firefox. I have tampermonkey and it says the script is enabled but it does not seem to be running when i am on the gemini web app for desktop. Before I investigate further myself I just wanted to ask if you had tried running it on firefox and it works for you so I'd know if it's just a problem on my side.

Thanks again,
Amir

**Comment by HenryGetz** [comment]
Thanks for trying to use it!

 I just tried running it on firefox, and it seems to run great (in website form-- is that what you meant by web app, or did you mean like a [Firefox PWA?](https://connect.mozilla.org/t5/ideas/bring-back-pwa-progressive-web-apps/idi-p/35)), but if you could answer some questions I can try to help you more:

When you are on the webpage, does Tampermonkey show it as enabled like the below? 
![image](https://github.com/HenryGetz/GeminiPilot/assets/109257119/7bd950ef-fe40-4c3b-b36d-dad6d0fdb2f5)

Is the Gemini Advanced logo on the right?
![image](https://github.com/HenryGetz/GeminiPilot/assets/109257119/cbe4283b-bf3f-458a-80d6-48dc87a6a4ee)

Are you on the latest versions of Firefox and Tampermonkey? Worse case scenario, it also wouldn't hurt to just try reinstalling Tampermonkey, (but at least the script.)

Thanks in advance!

**Comment by amirf147** [comment]
Ah, does it depend on having Gemini Advanced? I'm just using the free version currently. 

Enabled from the dashboard:
![image](https://github.com/HenryGetz/GeminiPilot/assets/7341565/1cd17b6f-8aad-4467-98d0-942959d0bbfb)

Tampermonkey does not show it being enabled:
![image](https://github.com/HenryGetz/GeminiPilot/assets/7341565/cbce74d5-f683-435f-a083-194b8d94b88b)

If it does not require Gemini Advanced, I can report back on whether it's some of my other extensions that are causing the issue such as vimium c when I get more time.

Thanks for your quick response by the way!

**Comment by HenryGetz** [comment]
Yeah of course! 

I just double checked, logging into one of my accounts that doesn't have advanced, and it worked there too, on the exact same URL you are on too (https://gemini.google.com/app.)

Ironically enough, I had this exact same error on one of my accounts on Brave yesterday, and the key was uninstalling and reinstalling Tampermonkey itself, for whatever reason. Idk if that will actually be the golden ticket for you too, but: 

- if you haven't tried [reinstalling the script](https://greasyfork.org/en/scripts/498823-gemini-keyboard-shortcuts), I would do that first. 
- If there's still problems, try uninstalling and reinstalling Tampermonkey. 
- If that doesn't work, try disabling every other extension than Tampermonkey to see if there's conflicts

Hopefully that helps!

**Comment by amirf147** [comment]
OK nice! Reinstalling the script fixed the issue and it is now working! Thanks for the help!

**Comment by HenryGetz** [comment]
I just figured it out... I forgot a "*" in the @match declaration. So sorry about that!! Thank you so much for making an issue, that one character literally has probably broken this for everyone trying to use it

**Comment by amirf147** [comment]
Ok great! I see you added some new commits. I went to go upgrade and it weirdly says that it will downgrade to the new version:
![image](https://github.com/HenryGetz/GeminiPilot/assets/7341565/dddbb585-1b5e-4972-a521-8fd41033db18)
Ah ok, perhaps it's because it was 1.11 which is eleven and now it's 1.2x xD

**Comment by HenryGetz** [comment]
Ah geez. You can tell it's my first time doing this ahaha, gotta start somewhere I guess. Made sense in my head 😂

**Comment by amirf147** [comment]
No it's great that you made this, it really helps for my accessibility needs, very thankful! Interestingly enough, it was recommended by gemini:
![image](https://github.com/HenryGetz/GeminiPilot/assets/7341565/404a6386-129c-4b7a-a888-f17fb655030a)
